SELECT a1.ANIMAL_ID, a1.ANIMAL_TYPE, a1.NAME
FROM ANIMAL_OUTS as a1 JOIN ANIMAL_INS as a2
    ON a1.ANIMAL_ID = a2.ANIMAL_ID
WHERE a2.SEX_UPON_INTAKE LIKE 'Intact%' AND (a1.SEX_UPON_OUTCOME LIKE 'Neutered%' OR a1.SEX_UPON_OUTCOME LIKE 'Spayed%')
ORDER BY ANIMAL_ID ASC;